/* eslint-disable */
// Generated automatically by nearley, version 2.20.1
// http://github.com/Hardmath123/nearley
export const grammar = (function () {

var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "START", "symbols": ["_", "PLAY", "_"], "postprocess": (_d) => _d[1]},
    {"name": "PLAY", "symbols": ["EVENT"], "postprocess": (_d) => [_d[0]]},
    {"name": "PLAY", "symbols": ["PLAY", "DELIMITER", "EVENT"], "postprocess": (_d) => [..._d[0], _d[2]]},
    {"name": "DELIMITER", "symbols": ["_", {"literal":","}, "_"], "postprocess": (_d) => null},
    {"name": "DELIMITER$string$1", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DELIMITER", "symbols": ["_", "DELIMITER$string$1", "_"], "postprocess": (_d) => null},
    {"name": "DELIMITER$string$2", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DELIMITER", "symbols": ["_", "DELIMITER$string$2", "_"], "postprocess": (_d) => null},
    {"name": "EVENT", "symbols": ["PITCH"], "postprocess": (_d) => _d[0]},
    {"name": "EVENT", "symbols": ["BIP"], "postprocess": (_d) => _d[0]},
    {"name": "EVENT", "symbols": ["OUT"], "postprocess": (_d) => _d[0]},
    {"name": "EVENT", "symbols": ["RUNNER_ACTION"], "postprocess": (_d) => _d[0]},
    {"name": "EVENT", "symbols": ["SUB"], "postprocess": (_d) => _d[0]},
    {"name": "PITCH$string$1", "symbols": [{"literal":"b"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PITCH", "symbols": ["PITCH$string$1"], "postprocess": (_d) => ({ type: 'PITCH', outcome: 'ball' })},
    {"name": "PITCH$string$2", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"k"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PITCH", "symbols": ["PITCH$string$2"], "postprocess": (_d) => ({ type: 'PITCH', outcome: 'strike' })},
    {"name": "PITCH$string$3", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PITCH", "symbols": ["PITCH$string$3"], "postprocess": (_d) => ({ type: 'PITCH', outcome: 'foul' })},
    {"name": "BIP$string$1", "symbols": [{"literal":"s"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BIP", "symbols": ["BIP$string$1"], "postprocess": (_d) => ({ type: 'BIP', result: '1B' })},
    {"name": "BIP$string$2", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"u"}, {"literal":"b"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BIP", "symbols": ["BIP$string$2"], "postprocess": (_d) => ({ type: 'BIP', result: '2B' })},
    {"name": "BIP$string$3", "symbols": [{"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"p"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BIP", "symbols": ["BIP$string$3"], "postprocess": (_d) => ({ type: 'BIP', result: '3B' })},
    {"name": "BIP$string$4", "symbols": [{"literal":"h"}, {"literal":"o"}, {"literal":"m"}, {"literal":"e"}, {"literal":"r"}, {"literal":"u"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BIP", "symbols": ["BIP$string$4"], "postprocess": (_d) => ({ type: 'BIP', result: 'HR' })},
    {"name": "OUT$string$1", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"k"}, {"literal":"e"}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OUT", "symbols": ["OUT$string$1"], "postprocess": (_d) => ({ type: 'OUT', result: 'strikeout' })},
    {"name": "OUT$string$2", "symbols": [{"literal":"f"}, {"literal":"l"}, {"literal":"y"}, {"literal":" "}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OUT", "symbols": ["OUT$string$2"], "postprocess": (_d) => ({ type: 'OUT', result: 'fly out' })},
    {"name": "OUT$string$3", "symbols": [{"literal":"g"}, {"literal":"r"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"d"}, {"literal":" "}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OUT", "symbols": ["OUT$string$3"], "postprocess": (_d) => ({ type: 'OUT', result: 'ground out' })},
    {"name": "RUNNER_ACTION$string$1", "symbols": [{"literal":"r"}, {"literal":"u"}, {"literal":"n"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RUNNER_ACTION$string$2", "symbols": [{"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RUNNER_ACTION", "symbols": ["RUNNER_ACTION$string$1", "_", "RUNNER_ACTION$string$2", "_", "BASE"], "postprocess": (_d) => ({ type: 'RUNNER_ADVANCE', base: _d[4] })},
    {"name": "RUNNER_ACTION$string$3", "symbols": [{"literal":"r"}, {"literal":"u"}, {"literal":"n"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RUNNER_ACTION$string$4", "symbols": [{"literal":"s"}, {"literal":"c"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RUNNER_ACTION", "symbols": ["RUNNER_ACTION$string$3", "_", "RUNNER_ACTION$string$4"], "postprocess": (_d) => ({ type: 'RUNNER_ADVANCE', base: 'home' })},
    {"name": "BASE$string$1", "symbols": [{"literal":"f"}, {"literal":"i"}, {"literal":"r"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BASE", "symbols": ["BASE$string$1"], "postprocess": (_d) => '1B'},
    {"name": "BASE$string$2", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BASE", "symbols": ["BASE$string$2"], "postprocess": (_d) => '2B'},
    {"name": "BASE$string$3", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"r"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BASE", "symbols": ["BASE$string$3"], "postprocess": (_d) => '3B'},
    {"name": "BASE$string$4", "symbols": [{"literal":"h"}, {"literal":"o"}, {"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BASE", "symbols": ["BASE$string$4"], "postprocess": (_d) => 'home'},
    {"name": "SUB$string$1", "symbols": [{"literal":"p"}, {"literal":"i"}, {"literal":"n"}, {"literal":"c"}, {"literal":"h"}, {"literal":" "}, {"literal":"r"}, {"literal":"u"}, {"literal":"n"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUB", "symbols": ["SUB$string$1", "_", "PLAYER_REF"], "postprocess": (_d) => ({ type: 'SUBSTITUTION', player: _d[2], replaced: null })},
    {"name": "SUB$string$2", "symbols": [{"literal":"p"}, {"literal":"i"}, {"literal":"n"}, {"literal":"c"}, {"literal":"h"}, {"literal":" "}, {"literal":"r"}, {"literal":"u"}, {"literal":"n"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUB$string$3", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUB", "symbols": ["SUB$string$2", "_", "PLAYER_REF", "_", "SUB$string$3", "_", "PLAYER_REF"], "postprocess": (_d) => ({ type: 'SUBSTITUTION', player: _d[2], replaced: _d[6] })},
    {"name": "SUB$string$4", "symbols": [{"literal":"p"}, {"literal":"i"}, {"literal":"t"}, {"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"c"}, {"literal":"h"}, {"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUB", "symbols": ["SUB$string$4", "_", "PLAYER_REF"], "postprocess": (_d) => ({ type: 'PITCHER_UPDATE', player: _d[2], replaced: null })},
    {"name": "SUB$string$5", "symbols": [{"literal":"p"}, {"literal":"i"}, {"literal":"t"}, {"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"c"}, {"literal":"h"}, {"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUB$string$6", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUB", "symbols": ["SUB$string$5", "_", "PLAYER_REF", "_", "SUB$string$6", "_", "PLAYER_REF"], "postprocess": (_d) => ({ type: 'PITCHER_UPDATE', player: _d[2], replaced: _d[6] })},
    {"name": "PLAYER_REF$string$1", "symbols": [{"literal":"n"}, {"literal":"u"}, {"literal":"m"}, {"literal":"b"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLAYER_REF", "symbols": ["PLAYER_REF$string$1", "_", "int"], "postprocess": (_d) => ({ jersey: _d[2] })},
    {"name": "PLAYER_REF", "symbols": ["int"], "postprocess": (_d) => ({ jersey: _d[0] })},
    {"name": "DIGIT", "symbols": [/[0-9]/], "postprocess": (_d) => _d[0]},
    {"name": "int", "symbols": ["DIGIT"], "postprocess": (_d) => parseInt(_d[0])},
    {"name": "int", "symbols": ["int", "DIGIT"], "postprocess": (_d) => parseInt(_d[0].toString() + _d[1])},
    {"name": "_", "symbols": [], "postprocess": (_d) => null},
    {"name": "_", "symbols": ["_", "wschar"], "postprocess": (_d) => null},
    {"name": "wschar", "symbols": [/[ \t\n\r]/], "postprocess": (_d) => null}
]
  , ParserStart: "START"
}
return grammar;
})();
