/* eslint-disable */
// Generated automatically by nearley, version 2.20.1
// http://github.com/Hardmath123/nearley
export const grammar = (function () {

var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "START", "symbols": ["_", "PLAY", "_"], "postprocess": (_d) => _d[1]},
    {"name": "PLAY", "symbols": ["EVENT"], "postprocess": (_d) => [_d[0]]},
    {"name": "PLAY", "symbols": ["PLAY", "DELIMITER", "EVENT"], "postprocess": (_d) => [..._d[0], _d[2]]},
    {"name": "DELIMITER", "symbols": ["_", {"literal":","}, "_"], "postprocess": (_d) => null},
    {"name": "DELIMITER$string$1", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DELIMITER", "symbols": ["_", "DELIMITER$string$1", "_"], "postprocess": (_d) => null},
    {"name": "DELIMITER$string$2", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DELIMITER", "symbols": ["_", "DELIMITER$string$2", "_"], "postprocess": (_d) => null},
    {"name": "EVENT", "symbols": ["PITCH"], "postprocess": (_d) => _d[0]},
    {"name": "EVENT", "symbols": ["BIP"], "postprocess": (_d) => _d[0]},
    {"name": "EVENT", "symbols": ["OUT"], "postprocess": (_d) => _d[0]},
    {"name": "EVENT", "symbols": ["RUNNER_ACTION"], "postprocess": (_d) => _d[0]},
    {"name": "EVENT", "symbols": ["SUB"], "postprocess": (_d) => _d[0]},
    {"name": "EVENT", "symbols": ["WALK"], "postprocess": (_d) => _d[0]},
    {"name": "EVENT", "symbols": ["HBP"], "postprocess": (_d) => _d[0]},
    {"name": "EVENT", "symbols": ["ERROR_PLAY"], "postprocess": (_d) => _d[0]},
    {"name": "EVENT", "symbols": ["FC_PLAY"], "postprocess": (_d) => _d[0]},
    {"name": "EVENT", "symbols": ["STEAL_PLAY"], "postprocess": (_d) => _d[0]},
    {"name": "EVENT", "symbols": ["CS_PLAY"], "postprocess": (_d) => _d[0]},
    {"name": "EVENT", "symbols": ["WP_PB"], "postprocess": (_d) => _d[0]},
    {"name": "EVENT", "symbols": ["STATE_ASSERTION"], "postprocess": (_d) => _d[0]},
    {"name": "PITCH$string$1", "symbols": [{"literal":"b"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PITCH", "symbols": ["PITCH$string$1"], "postprocess": (_d) => ({ type: 'PITCH', outcome: 'ball' })},
    {"name": "PITCH$string$2", "symbols": [{"literal":"b"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PITCH", "symbols": ["PITCH$string$2", "_", "int"], "postprocess": (_d) => ({ type: 'PITCH', outcome: 'ball' })},
    {"name": "PITCH$string$3", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"k"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PITCH", "symbols": ["PITCH$string$3"], "postprocess": (_d) => ({ type: 'PITCH', outcome: 'strike' })},
    {"name": "PITCH$string$4", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"k"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PITCH", "symbols": ["PITCH$string$4", "_", "int"], "postprocess": (_d) => ({ type: 'PITCH', outcome: 'strike' })},
    {"name": "PITCH$string$5", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PITCH", "symbols": ["PITCH$string$5"], "postprocess": (_d) => ({ type: 'PITCH', outcome: 'foul' })},
    {"name": "PITCH$string$6", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PITCH$string$7", "symbols": [{"literal":"b"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PITCH", "symbols": ["PITCH$string$6", "_", "PITCH$string$7"], "postprocess": (_d) => ({ type: 'PITCH', outcome: 'foul' })},
    {"name": "BIP$string$1", "symbols": [{"literal":"s"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BIP", "symbols": ["BIP$string$1"], "postprocess": (_d) => ({ type: 'BIP', result: '1B' })},
    {"name": "BIP$string$2", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"u"}, {"literal":"b"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BIP", "symbols": ["BIP$string$2"], "postprocess": (_d) => ({ type: 'BIP', result: '2B' })},
    {"name": "BIP$string$3", "symbols": [{"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"p"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BIP", "symbols": ["BIP$string$3"], "postprocess": (_d) => ({ type: 'BIP', result: '3B' })},
    {"name": "BIP$string$4", "symbols": [{"literal":"h"}, {"literal":"o"}, {"literal":"m"}, {"literal":"e"}, {"literal":"r"}, {"literal":"u"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BIP", "symbols": ["BIP$string$4"], "postprocess": (_d) => ({ type: 'BIP', result: 'HR' })},
    {"name": "BIP$string$5", "symbols": [{"literal":"s"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BIP$string$6", "symbols": [{"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BIP", "symbols": ["BIP$string$5", "_", "BIP$string$6", "_", "POSITION"], "postprocess": (_d) => ({ type: 'BIP', result: '1B', pos: _d[4] })},
    {"name": "BIP$string$7", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"u"}, {"literal":"b"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BIP$string$8", "symbols": [{"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BIP", "symbols": ["BIP$string$7", "_", "BIP$string$8", "_", "POSITION"], "postprocess": (_d) => ({ type: 'BIP', result: '2B', pos: _d[4] })},
    {"name": "BIP$string$9", "symbols": [{"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"p"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BIP$string$10", "symbols": [{"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BIP", "symbols": ["BIP$string$9", "_", "BIP$string$10", "_", "POSITION"], "postprocess": (_d) => ({ type: 'BIP', result: '3B', pos: _d[4] })},
    {"name": "BIP$string$11", "symbols": [{"literal":"h"}, {"literal":"o"}, {"literal":"m"}, {"literal":"e"}, {"literal":"r"}, {"literal":"u"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BIP$string$12", "symbols": [{"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BIP", "symbols": ["BIP$string$11", "_", "BIP$string$12", "_", "POSITION"], "postprocess": (_d) => ({ type: 'BIP', result: 'HR', pos: _d[4] })},
    {"name": "OUT$string$1", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"k"}, {"literal":"e"}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OUT", "symbols": ["OUT$string$1"], "postprocess": (_d) => ({ type: 'OUT', result: 'strikeout' })},
    {"name": "OUT$string$2", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"k"}, {"literal":"e"}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OUT$string$3", "symbols": [{"literal":"l"}, {"literal":"o"}, {"literal":"o"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OUT", "symbols": ["OUT$string$2", "_", "OUT$string$3"], "postprocess": (_d) => ({ type: 'OUT', result: 'strikeout looking' })},
    {"name": "OUT$string$4", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"k"}, {"literal":"e"}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OUT$string$5", "symbols": [{"literal":"s"}, {"literal":"w"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OUT", "symbols": ["OUT$string$4", "_", "OUT$string$5"], "postprocess": (_d) => ({ type: 'OUT', result: 'strikeout swinging' })},
    {"name": "OUT$string$6", "symbols": [{"literal":"f"}, {"literal":"l"}, {"literal":"y"}, {"literal":" "}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OUT", "symbols": ["OUT$string$6"], "postprocess": (_d) => ({ type: 'OUT', result: 'fly out' })},
    {"name": "OUT$string$7", "symbols": [{"literal":"g"}, {"literal":"r"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"d"}, {"literal":" "}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OUT", "symbols": ["OUT$string$7"], "postprocess": (_d) => ({ type: 'OUT', result: 'ground out' })},
    {"name": "OUT$string$8", "symbols": [{"literal":"f"}, {"literal":"l"}, {"literal":"y"}, {"literal":" "}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OUT$string$9", "symbols": [{"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OUT", "symbols": ["OUT$string$8", "_", "OUT$string$9", "_", "POSITION"], "postprocess": (_d) => ({ type: 'OUT', result: 'fly out', pos: _d[4] })},
    {"name": "OUT$string$10", "symbols": [{"literal":"g"}, {"literal":"r"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"d"}, {"literal":" "}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OUT$string$11", "symbols": [{"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OUT", "symbols": ["OUT$string$10", "_", "OUT$string$11", "_", "POSITION"], "postprocess": (_d) => ({ type: 'OUT', result: 'ground out', pos: _d[4] })},
    {"name": "OUT$string$12", "symbols": [{"literal":"g"}, {"literal":"r"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"d"}, {"literal":" "}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OUT", "symbols": ["OUT$string$12", "_", "int", "_", {"literal":"-"}, "_", "int"], "postprocess": (_d) => ({ type: 'OUT', result: 'ground out', sequence: _d[2].toString() + '-' + _d[6].toString() })},
    {"name": "OUT$string$13", "symbols": [{"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}, {"literal":" "}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OUT", "symbols": ["OUT$string$13"], "postprocess": (_d) => ({ type: 'OUT', result: 'line out' })},
    {"name": "OUT$string$14", "symbols": [{"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}, {"literal":" "}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OUT$string$15", "symbols": [{"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OUT", "symbols": ["OUT$string$14", "_", "OUT$string$15", "_", "POSITION"], "postprocess": (_d) => ({ type: 'OUT', result: 'line out', pos: _d[4] })},
    {"name": "OUT$string$16", "symbols": [{"literal":"p"}, {"literal":"o"}, {"literal":"p"}, {"literal":" "}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OUT", "symbols": ["OUT$string$16"], "postprocess": (_d) => ({ type: 'OUT', result: 'pop out' })},
    {"name": "OUT$string$17", "symbols": [{"literal":"p"}, {"literal":"o"}, {"literal":"p"}, {"literal":" "}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OUT$string$18", "symbols": [{"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OUT", "symbols": ["OUT$string$17", "_", "OUT$string$18", "_", "POSITION"], "postprocess": (_d) => ({ type: 'OUT', result: 'pop out', pos: _d[4] })},
    {"name": "RUNNER_ACTION$string$1", "symbols": [{"literal":"r"}, {"literal":"u"}, {"literal":"n"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RUNNER_ACTION$string$2", "symbols": [{"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RUNNER_ACTION", "symbols": ["RUNNER_ACTION$string$1", "_", "RUNNER_ACTION$string$2", "_", "BASE"], "postprocess": (_d) => ({ type: 'RUNNER_ADVANCE', base: _d[4] })},
    {"name": "RUNNER_ACTION$string$3", "symbols": [{"literal":"r"}, {"literal":"u"}, {"literal":"n"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RUNNER_ACTION$string$4", "symbols": [{"literal":"s"}, {"literal":"c"}, {"literal":"o"}, {"literal":"r"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RUNNER_ACTION", "symbols": ["RUNNER_ACTION$string$3", "_", "RUNNER_ACTION$string$4"], "postprocess": (_d) => ({ type: 'RUNNER_ADVANCE', base: 'home' })},
    {"name": "BASE$string$1", "symbols": [{"literal":"f"}, {"literal":"i"}, {"literal":"r"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BASE", "symbols": ["BASE$string$1"], "postprocess": (_d) => '1B'},
    {"name": "BASE$string$2", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BASE", "symbols": ["BASE$string$2"], "postprocess": (_d) => '2B'},
    {"name": "BASE$string$3", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"r"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BASE", "symbols": ["BASE$string$3"], "postprocess": (_d) => '3B'},
    {"name": "BASE$string$4", "symbols": [{"literal":"h"}, {"literal":"o"}, {"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BASE", "symbols": ["BASE$string$4"], "postprocess": (_d) => 'home'},
    {"name": "SUB$string$1", "symbols": [{"literal":"p"}, {"literal":"i"}, {"literal":"n"}, {"literal":"c"}, {"literal":"h"}, {"literal":" "}, {"literal":"r"}, {"literal":"u"}, {"literal":"n"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUB", "symbols": ["SUB$string$1", "_", "PLAYER_REF"], "postprocess": (_d) => ({ type: 'SUBSTITUTION', player: _d[2], replaced: null })},
    {"name": "SUB$string$2", "symbols": [{"literal":"p"}, {"literal":"i"}, {"literal":"n"}, {"literal":"c"}, {"literal":"h"}, {"literal":" "}, {"literal":"r"}, {"literal":"u"}, {"literal":"n"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUB$string$3", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUB", "symbols": ["SUB$string$2", "_", "PLAYER_REF", "_", "SUB$string$3", "_", "PLAYER_REF"], "postprocess": (_d) => ({ type: 'SUBSTITUTION', player: _d[2], replaced: _d[6] })},
    {"name": "SUB$string$4", "symbols": [{"literal":"p"}, {"literal":"i"}, {"literal":"t"}, {"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"c"}, {"literal":"h"}, {"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUB", "symbols": ["SUB$string$4", "_", "PLAYER_REF"], "postprocess": (_d) => ({ type: 'PITCHER_UPDATE', player: _d[2], replaced: null })},
    {"name": "SUB$string$5", "symbols": [{"literal":"p"}, {"literal":"i"}, {"literal":"t"}, {"literal":"c"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":" "}, {"literal":"c"}, {"literal":"h"}, {"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUB$string$6", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SUB", "symbols": ["SUB$string$5", "_", "PLAYER_REF", "_", "SUB$string$6", "_", "PLAYER_REF"], "postprocess": (_d) => ({ type: 'PITCHER_UPDATE', player: _d[2], replaced: _d[6] })},
    {"name": "PLAYER_REF$string$1", "symbols": [{"literal":"n"}, {"literal":"u"}, {"literal":"m"}, {"literal":"b"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "PLAYER_REF", "symbols": ["PLAYER_REF$string$1", "_", "int"], "postprocess": (_d) => ({ jersey: _d[2] })},
    {"name": "PLAYER_REF", "symbols": ["int"], "postprocess": (_d) => ({ jersey: _d[0] })},
    {"name": "WALK$string$1", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"l"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WALK", "symbols": ["WALK$string$1"], "postprocess": (_d) => ({ type: 'WALK' })},
    {"name": "WALK$string$2", "symbols": [{"literal":"b"}, {"literal":"a"}, {"literal":"s"}, {"literal":"e"}, {"literal":" "}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"b"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WALK", "symbols": ["WALK$string$2"], "postprocess": (_d) => ({ type: 'WALK' })},
    {"name": "WALK$string$3", "symbols": [{"literal":"b"}, {"literal":"b"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WALK", "symbols": ["WALK$string$3"], "postprocess": (_d) => ({ type: 'WALK' })},
    {"name": "HBP$string$1", "symbols": [{"literal":"h"}, {"literal":"i"}, {"literal":"t"}, {"literal":" "}, {"literal":"b"}, {"literal":"y"}, {"literal":" "}, {"literal":"p"}, {"literal":"i"}, {"literal":"t"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HBP", "symbols": ["HBP$string$1"], "postprocess": (_d) => ({ type: 'HBP' })},
    {"name": "HBP$string$2", "symbols": [{"literal":"h"}, {"literal":"b"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HBP", "symbols": ["HBP$string$2"], "postprocess": (_d) => ({ type: 'HBP' })},
    {"name": "ERROR_PLAY$string$1", "symbols": [{"literal":"s"}, {"literal":"a"}, {"literal":"f"}, {"literal":"e"}, {"literal":" "}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"e"}, {"literal":"r"}, {"literal":"r"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ERROR_PLAY", "symbols": ["ERROR_PLAY$string$1"], "postprocess": (_d) => ({ type: 'ERROR', pos: null })},
    {"name": "ERROR_PLAY$string$2", "symbols": [{"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"c"}, {"literal":"h"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"e"}, {"literal":"r"}, {"literal":"r"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ERROR_PLAY", "symbols": ["ERROR_PLAY$string$2"], "postprocess": (_d) => ({ type: 'ERROR', pos: null })},
    {"name": "ERROR_PLAY$string$3", "symbols": [{"literal":"s"}, {"literal":"a"}, {"literal":"f"}, {"literal":"e"}, {"literal":" "}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"e"}, {"literal":"r"}, {"literal":"r"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ERROR_PLAY$string$4", "symbols": [{"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ERROR_PLAY", "symbols": ["ERROR_PLAY$string$3", "_", "ERROR_PLAY$string$4", "_", "POSITION"], "postprocess": (_d) => ({ type: 'ERROR', pos: _d[4] })},
    {"name": "ERROR_PLAY$string$5", "symbols": [{"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"c"}, {"literal":"h"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"e"}, {"literal":"r"}, {"literal":"r"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ERROR_PLAY$string$6", "symbols": [{"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ERROR_PLAY", "symbols": ["ERROR_PLAY$string$5", "_", "ERROR_PLAY$string$6", "_", "POSITION"], "postprocess": (_d) => ({ type: 'ERROR', pos: _d[4] })},
    {"name": "ERROR_PLAY$string$7", "symbols": [{"literal":"e"}, {"literal":"r"}, {"literal":"r"}, {"literal":"o"}, {"literal":"r"}, {"literal":" "}, {"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ERROR_PLAY", "symbols": ["ERROR_PLAY$string$7", "_", "POSITION"], "postprocess": (_d) => ({ type: 'ERROR', pos: _d[2] })},
    {"name": "FC_PLAY$string$1", "symbols": [{"literal":"f"}, {"literal":"i"}, {"literal":"e"}, {"literal":"l"}, {"literal":"d"}, {"literal":"e"}, {"literal":"r"}, {"literal":"'"}, {"literal":"s"}, {"literal":" "}, {"literal":"c"}, {"literal":"h"}, {"literal":"o"}, {"literal":"i"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FC_PLAY", "symbols": ["FC_PLAY$string$1"], "postprocess": (_d) => ({ type: 'FIELDERS_CHOICE', pos: null })},
    {"name": "FC_PLAY$string$2", "symbols": [{"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"c"}, {"literal":"h"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"f"}, {"literal":"i"}, {"literal":"e"}, {"literal":"l"}, {"literal":"d"}, {"literal":"e"}, {"literal":"r"}, {"literal":"'"}, {"literal":"s"}, {"literal":" "}, {"literal":"c"}, {"literal":"h"}, {"literal":"o"}, {"literal":"i"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FC_PLAY", "symbols": ["FC_PLAY$string$2"], "postprocess": (_d) => ({ type: 'FIELDERS_CHOICE', pos: null })},
    {"name": "FC_PLAY$string$3", "symbols": [{"literal":"f"}, {"literal":"i"}, {"literal":"e"}, {"literal":"l"}, {"literal":"d"}, {"literal":"e"}, {"literal":"r"}, {"literal":"'"}, {"literal":"s"}, {"literal":" "}, {"literal":"c"}, {"literal":"h"}, {"literal":"o"}, {"literal":"i"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FC_PLAY$string$4", "symbols": [{"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FC_PLAY", "symbols": ["FC_PLAY$string$3", "_", "FC_PLAY$string$4", "_", "POSITION"], "postprocess": (_d) => ({ type: 'FIELDERS_CHOICE', pos: _d[4] })},
    {"name": "FC_PLAY$string$5", "symbols": [{"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"c"}, {"literal":"h"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"o"}, {"literal":"n"}, {"literal":" "}, {"literal":"f"}, {"literal":"i"}, {"literal":"e"}, {"literal":"l"}, {"literal":"d"}, {"literal":"e"}, {"literal":"r"}, {"literal":"'"}, {"literal":"s"}, {"literal":" "}, {"literal":"c"}, {"literal":"h"}, {"literal":"o"}, {"literal":"i"}, {"literal":"c"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FC_PLAY$string$6", "symbols": [{"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FC_PLAY", "symbols": ["FC_PLAY$string$5", "_", "FC_PLAY$string$6", "_", "POSITION"], "postprocess": (_d) => ({ type: 'FIELDERS_CHOICE', pos: _d[4] })},
    {"name": "FC_PLAY$string$7", "symbols": [{"literal":"f"}, {"literal":"c"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FC_PLAY", "symbols": ["FC_PLAY$string$7"], "postprocess": (_d) => ({ type: 'FIELDERS_CHOICE', pos: null })},
    {"name": "STEAL_PLAY$string$1", "symbols": [{"literal":"r"}, {"literal":"u"}, {"literal":"n"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}, {"literal":"s"}, {"literal":"t"}, {"literal":"e"}, {"literal":"a"}, {"literal":"l"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "STEAL_PLAY", "symbols": ["STEAL_PLAY$string$1", "_", "BASE"], "postprocess": (_d) => ({ type: 'STEAL', base: _d[2] })},
    {"name": "STEAL_PLAY$string$2", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"o"}, {"literal":"l"}, {"literal":"e"}, {"literal":"n"}, {"literal":" "}, {"literal":"b"}, {"literal":"a"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "STEAL_PLAY", "symbols": ["STEAL_PLAY$string$2"], "postprocess": (_d) => ({ type: 'STEAL', base: null })},
    {"name": "STEAL_PLAY$string$3", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"o"}, {"literal":"l"}, {"literal":"e"}, {"literal":"n"}, {"literal":" "}, {"literal":"b"}, {"literal":"a"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "STEAL_PLAY", "symbols": ["STEAL_PLAY$string$3", "_", "BASE"], "postprocess": (_d) => ({ type: 'STEAL', base: _d[2] })},
    {"name": "CS_PLAY$string$1", "symbols": [{"literal":"r"}, {"literal":"u"}, {"literal":"n"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}, {"literal":"c"}, {"literal":"a"}, {"literal":"u"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":" "}, {"literal":"s"}, {"literal":"t"}, {"literal":"e"}, {"literal":"a"}, {"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CS_PLAY", "symbols": ["CS_PLAY$string$1", "_", "BASE"], "postprocess": (_d) => ({ type: 'CAUGHT_STEALING', base: _d[3] })},
    {"name": "CS_PLAY$string$2", "symbols": [{"literal":"r"}, {"literal":"u"}, {"literal":"n"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}, {"literal":"c"}, {"literal":"a"}, {"literal":"u"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":" "}, {"literal":"s"}, {"literal":"t"}, {"literal":"e"}, {"literal":"a"}, {"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CS_PLAY", "symbols": ["CS_PLAY$string$2"], "postprocess": (_d) => ({ type: 'CAUGHT_STEALING', base: null })},
    {"name": "CS_PLAY$string$3", "symbols": [{"literal":"c"}, {"literal":"a"}, {"literal":"u"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":" "}, {"literal":"s"}, {"literal":"t"}, {"literal":"e"}, {"literal":"a"}, {"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CS_PLAY", "symbols": ["CS_PLAY$string$3", "_", "BASE"], "postprocess": (_d) => ({ type: 'CAUGHT_STEALING', base: _d[2] })},
    {"name": "WP_PB$string$1", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"l"}, {"literal":"d"}, {"literal":" "}, {"literal":"p"}, {"literal":"i"}, {"literal":"t"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WP_PB", "symbols": ["WP_PB$string$1"], "postprocess": (_d) => ({ type: 'WILD_PITCH' })},
    {"name": "WP_PB$string$2", "symbols": [{"literal":"p"}, {"literal":"a"}, {"literal":"s"}, {"literal":"s"}, {"literal":"e"}, {"literal":"d"}, {"literal":" "}, {"literal":"b"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WP_PB", "symbols": ["WP_PB$string$2"], "postprocess": (_d) => ({ type: 'PASSED_BALL' })},
    {"name": "STATE_ASSERTION$string$1", "symbols": [{"literal":"b"}, {"literal":"a"}, {"literal":"s"}, {"literal":"e"}, {"literal":"s"}, {"literal":" "}, {"literal":"l"}, {"literal":"o"}, {"literal":"a"}, {"literal":"d"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "STATE_ASSERTION", "symbols": ["STATE_ASSERTION$string$1"], "postprocess": (_d) => ({ type: 'STATE_ASSERTION', bases: [1, 2, 3] })},
    {"name": "STATE_ASSERTION$string$2", "symbols": [{"literal":"b"}, {"literal":"a"}, {"literal":"s"}, {"literal":"e"}, {"literal":"s"}, {"literal":" "}, {"literal":"e"}, {"literal":"m"}, {"literal":"p"}, {"literal":"t"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "STATE_ASSERTION", "symbols": ["STATE_ASSERTION$string$2"], "postprocess": (_d) => ({ type: 'STATE_ASSERTION', bases: [] })},
    {"name": "STATE_ASSERTION$string$3", "symbols": [{"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "STATE_ASSERTION", "symbols": ["ASSERTION_RUNNERS", "_", "STATE_ASSERTION$string$3", "_", "BASE", "_", "AND_OR_COMMA", "_", "BASE"], "postprocess": (_d) => { const baseToNum = { '1B': 1, '2B': 2, '3B': 3, 'home': 4 }; return { type: 'STATE_ASSERTION', bases: [baseToNum[_d[4]], baseToNum[_d[8]]].sort() }; }},
    {"name": "STATE_ASSERTION$string$4", "symbols": [{"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "STATE_ASSERTION", "symbols": ["ASSERTION_RUNNERS", "_", "STATE_ASSERTION$string$4", "_", "BASE"], "postprocess": (_d) => { const baseToNum = { '1B': 1, '2B': 2, '3B': 3, 'home': 4 }; return { type: 'STATE_ASSERTION', bases: [baseToNum[_d[4]]] }; }},
    {"name": "ASSERTION_RUNNERS$string$1", "symbols": [{"literal":"r"}, {"literal":"u"}, {"literal":"n"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ASSERTION_RUNNERS", "symbols": ["ASSERTION_RUNNERS$string$1"]},
    {"name": "ASSERTION_RUNNERS$string$2", "symbols": [{"literal":"r"}, {"literal":"u"}, {"literal":"n"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ASSERTION_RUNNERS", "symbols": ["ASSERTION_RUNNERS$string$2"]},
    {"name": "AND_OR_COMMA$string$1", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AND_OR_COMMA", "symbols": ["AND_OR_COMMA$string$1"]},
    {"name": "AND_OR_COMMA", "symbols": [{"literal":","}]},
    {"name": "POSITION$string$1", "symbols": [{"literal":"p"}, {"literal":"i"}, {"literal":"t"}, {"literal":"c"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSITION", "symbols": ["POSITION$string$1"], "postprocess": (_d) => '1'},
    {"name": "POSITION$string$2", "symbols": [{"literal":"c"}, {"literal":"a"}, {"literal":"t"}, {"literal":"c"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSITION", "symbols": ["POSITION$string$2"], "postprocess": (_d) => '2'},
    {"name": "POSITION$string$3", "symbols": [{"literal":"f"}, {"literal":"i"}, {"literal":"r"}, {"literal":"s"}, {"literal":"t"}, {"literal":" "}, {"literal":"b"}, {"literal":"a"}, {"literal":"s"}, {"literal":"e"}, {"literal":"m"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSITION", "symbols": ["POSITION$string$3"], "postprocess": (_d) => '3'},
    {"name": "POSITION$string$4", "symbols": [{"literal":"f"}, {"literal":"i"}, {"literal":"r"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSITION", "symbols": ["POSITION$string$4"], "postprocess": (_d) => '3'},
    {"name": "POSITION$string$5", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"d"}, {"literal":" "}, {"literal":"b"}, {"literal":"a"}, {"literal":"s"}, {"literal":"e"}, {"literal":"m"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSITION", "symbols": ["POSITION$string$5"], "postprocess": (_d) => '4'},
    {"name": "POSITION$string$6", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSITION", "symbols": ["POSITION$string$6"], "postprocess": (_d) => '4'},
    {"name": "POSITION$string$7", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"r"}, {"literal":"d"}, {"literal":" "}, {"literal":"b"}, {"literal":"a"}, {"literal":"s"}, {"literal":"e"}, {"literal":"m"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSITION", "symbols": ["POSITION$string$7"], "postprocess": (_d) => '5'},
    {"name": "POSITION$string$8", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"r"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSITION", "symbols": ["POSITION$string$8"], "postprocess": (_d) => '5'},
    {"name": "POSITION$string$9", "symbols": [{"literal":"s"}, {"literal":"h"}, {"literal":"o"}, {"literal":"r"}, {"literal":"t"}, {"literal":"s"}, {"literal":"t"}, {"literal":"o"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSITION", "symbols": ["POSITION$string$9"], "postprocess": (_d) => '6'},
    {"name": "POSITION$string$10", "symbols": [{"literal":"s"}, {"literal":"h"}, {"literal":"o"}, {"literal":"r"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSITION", "symbols": ["POSITION$string$10"], "postprocess": (_d) => '6'},
    {"name": "POSITION$string$11", "symbols": [{"literal":"l"}, {"literal":"e"}, {"literal":"f"}, {"literal":"t"}, {"literal":" "}, {"literal":"f"}, {"literal":"i"}, {"literal":"e"}, {"literal":"l"}, {"literal":"d"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSITION", "symbols": ["POSITION$string$11"], "postprocess": (_d) => '7'},
    {"name": "POSITION$string$12", "symbols": [{"literal":"l"}, {"literal":"e"}, {"literal":"f"}, {"literal":"t"}, {"literal":" "}, {"literal":"f"}, {"literal":"i"}, {"literal":"e"}, {"literal":"l"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSITION", "symbols": ["POSITION$string$12"], "postprocess": (_d) => '7'},
    {"name": "POSITION$string$13", "symbols": [{"literal":"l"}, {"literal":"e"}, {"literal":"f"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSITION", "symbols": ["POSITION$string$13"], "postprocess": (_d) => '7'},
    {"name": "POSITION$string$14", "symbols": [{"literal":"c"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}, {"literal":"f"}, {"literal":"i"}, {"literal":"e"}, {"literal":"l"}, {"literal":"d"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSITION", "symbols": ["POSITION$string$14"], "postprocess": (_d) => '8'},
    {"name": "POSITION$string$15", "symbols": [{"literal":"c"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":" "}, {"literal":"f"}, {"literal":"i"}, {"literal":"e"}, {"literal":"l"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSITION", "symbols": ["POSITION$string$15"], "postprocess": (_d) => '8'},
    {"name": "POSITION$string$16", "symbols": [{"literal":"c"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSITION", "symbols": ["POSITION$string$16"], "postprocess": (_d) => '8'},
    {"name": "POSITION$string$17", "symbols": [{"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":" "}, {"literal":"f"}, {"literal":"i"}, {"literal":"e"}, {"literal":"l"}, {"literal":"d"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSITION", "symbols": ["POSITION$string$17"], "postprocess": (_d) => '9'},
    {"name": "POSITION$string$18", "symbols": [{"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":" "}, {"literal":"f"}, {"literal":"i"}, {"literal":"e"}, {"literal":"l"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSITION", "symbols": ["POSITION$string$18"], "postprocess": (_d) => '9'},
    {"name": "POSITION$string$19", "symbols": [{"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "POSITION", "symbols": ["POSITION$string$19"], "postprocess": (_d) => '9'},
    {"name": "POSITION", "symbols": [/[1-9]/], "postprocess": (_d) => _d[0]},
    {"name": "DIGIT", "symbols": [/[0-9]/], "postprocess": (_d) => _d[0]},
    {"name": "int", "symbols": ["DIGIT"], "postprocess": (_d) => parseInt(_d[0])},
    {"name": "int", "symbols": ["int", "DIGIT"], "postprocess": (_d) => parseInt(_d[0].toString() + _d[1])},
    {"name": "_", "symbols": [], "postprocess": (_d) => null},
    {"name": "_", "symbols": ["_", "wschar"], "postprocess": (_d) => null},
    {"name": "wschar", "symbols": [/[ \t\n\r]/], "postprocess": (_d) => null}
]
  , ParserStart: "START"
}
return grammar;
})();
